[build]
command = "npm run build"
publish = "dist/cityhall-presentation/browser"

[build.environment]
NETLIFY_SKIP_FRAMEWORK_DETECTION = "true"

# Force Netlify not to run any build plugins (including the auto Angular runtime)
[[plugins]]
package = "@netlify/plugin-skip"
