[build]
command = "npm run build"
publish = "dist/cityhall-presentation/browser"

[build.environment]
NETLIFY_SKIP_FRAMEWORK_DETECTION = "true"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
